// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inference.proto
#ifndef GRPC_inference_2eproto__INCLUDED
#define GRPC_inference_2eproto__INCLUDED

#include "inference.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace org {
namespace pytorch {
namespace serve {
namespace grpc {
namespace inference {

class InferenceAPIsService final {
 public:
  static constexpr char const* service_full_name() {
    return "org.pytorch.serve.grpc.inference.InferenceAPIsService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Ping(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>> AsyncPing(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>>(AsyncPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>> PrepareAsyncPing(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>>(PrepareAsyncPingRaw(context, request, cq));
    }
    // Predictions entry point to get inference using default model version.
    virtual ::grpc::Status Predictions(::grpc::ClientContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest& request, ::org::pytorch::serve::grpc::inference::PredictionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::org::pytorch::serve::grpc::inference::PredictionResponse>> AsyncPredictions(::grpc::ClientContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest& request, ::grpc::CompletionQueue* cq) {
      std::cout << "in predictions before AsyncPredictionsRaw";
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::org::pytorch::serve::grpc::inference::PredictionResponse>>(AsyncPredictionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::org::pytorch::serve::grpc::inference::PredictionResponse>> PrepareAsyncPredictions(::grpc::ClientContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::org::pytorch::serve::grpc::inference::PredictionResponse>>(PrepareAsyncPredictionsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Ping(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Ping(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Predictions entry point to get inference using default model version.
      virtual void Predictions(::grpc::ClientContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest* request, ::org::pytorch::serve::grpc::inference::PredictionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Predictions(::grpc::ClientContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest* request, ::org::pytorch::serve::grpc::inference::PredictionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>* AsyncPingRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>* PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::org::pytorch::serve::grpc::inference::PredictionResponse>* AsyncPredictionsRaw(::grpc::ClientContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::org::pytorch::serve::grpc::inference::PredictionResponse>* PrepareAsyncPredictionsRaw(::grpc::ClientContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Ping(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>> AsyncPing(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>>(AsyncPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>> PrepareAsyncPing(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>>(PrepareAsyncPingRaw(context, request, cq));
    }
    ::grpc::Status Predictions(::grpc::ClientContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest& request, ::org::pytorch::serve::grpc::inference::PredictionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::org::pytorch::serve::grpc::inference::PredictionResponse>> AsyncPredictions(::grpc::ClientContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::org::pytorch::serve::grpc::inference::PredictionResponse>>(AsyncPredictionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::org::pytorch::serve::grpc::inference::PredictionResponse>> PrepareAsyncPredictions(::grpc::ClientContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::org::pytorch::serve::grpc::inference::PredictionResponse>>(PrepareAsyncPredictionsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Ping(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* response, std::function<void(::grpc::Status)>) override;
      void Ping(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Predictions(::grpc::ClientContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest* request, ::org::pytorch::serve::grpc::inference::PredictionResponse* response, std::function<void(::grpc::Status)>) override;
      void Predictions(::grpc::ClientContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest* request, ::org::pytorch::serve::grpc::inference::PredictionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>* AsyncPingRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>* PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::org::pytorch::serve::grpc::inference::PredictionResponse>* AsyncPredictionsRaw(::grpc::ClientContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::org::pytorch::serve::grpc::inference::PredictionResponse>* PrepareAsyncPredictionsRaw(::grpc::ClientContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Ping_;
    const ::grpc::internal::RpcMethod rpcmethod_Predictions_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Ping(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* response);
    // Predictions entry point to get inference using default model version.
    virtual ::grpc::Status Predictions(::grpc::ServerContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest* request, ::org::pytorch::serve::grpc::inference::PredictionResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Ping() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPing(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Predictions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Predictions() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Predictions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Predictions(::grpc::ServerContext* /*context*/, const ::org::pytorch::serve::grpc::inference::PredictionsRequest* /*request*/, ::org::pytorch::serve::grpc::inference::PredictionResponse* /*response*/) override {
      std::cout <<"In predictions before abort" << std::endl;
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPredictions(::grpc::ServerContext* context, ::org::pytorch::serve::grpc::inference::PredictionsRequest* request, ::grpc::ServerAsyncResponseWriter< ::org::pytorch::serve::grpc::inference::PredictionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
            std::cout <<"In predictions before abort" << std::endl;
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Ping<WithAsyncMethod_Predictions<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Ping() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* response) { return this->Ping(context, request, response); }));}
    void SetMessageAllocatorFor_Ping(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Ping(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Predictions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Predictions() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::org::pytorch::serve::grpc::inference::PredictionsRequest, ::org::pytorch::serve::grpc::inference::PredictionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::org::pytorch::serve::grpc::inference::PredictionsRequest* request, ::org::pytorch::serve::grpc::inference::PredictionResponse* response) { return this->Predictions(context, request, response); }));}
    void SetMessageAllocatorFor_Predictions(
        ::grpc::MessageAllocator< ::org::pytorch::serve::grpc::inference::PredictionsRequest, ::org::pytorch::serve::grpc::inference::PredictionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::org::pytorch::serve::grpc::inference::PredictionsRequest, ::org::pytorch::serve::grpc::inference::PredictionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Predictions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Predictions(::grpc::ServerContext* /*context*/, const ::org::pytorch::serve::grpc::inference::PredictionsRequest* /*request*/, ::org::pytorch::serve::grpc::inference::PredictionResponse* /*response*/) override {
            std::cout <<"In predictions before abort" << std::endl;

      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Predictions(
      ::grpc::CallbackServerContext* /*context*/, const ::org::pytorch::serve::grpc::inference::PredictionsRequest* /*request*/, ::org::pytorch::serve::grpc::inference::PredictionResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Ping<WithCallbackMethod_Predictions<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Ping() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Predictions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Predictions() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Predictions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Predictions(::grpc::ServerContext* /*context*/, const ::org::pytorch::serve::grpc::inference::PredictionsRequest* /*request*/, ::org::pytorch::serve::grpc::inference::PredictionResponse* /*response*/) override {
            std::cout <<"In predictions before abort" << std::endl;

      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Ping() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPing(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Predictions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Predictions() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Predictions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Predictions(::grpc::ServerContext* /*context*/, const ::org::pytorch::serve::grpc::inference::PredictionsRequest* /*request*/, ::org::pytorch::serve::grpc::inference::PredictionResponse* /*response*/) override {
           std::cout <<"In predictions before abort" << std::endl;

      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPredictions(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Ping() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Ping(context, request, response); }));
    }
    ~WithRawCallbackMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Ping(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Predictions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Predictions() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Predictions(context, request, response); }));
    }
    ~WithRawCallbackMethod_Predictions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Predictions(::grpc::ServerContext* /*context*/, const ::org::pytorch::serve::grpc::inference::PredictionsRequest* /*request*/, ::org::pytorch::serve::grpc::inference::PredictionResponse* /*response*/) override {
           std::cout <<"In predictions before abort" << std::endl;

      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Predictions(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { 
              std::cout <<"In predictions before abort" << std::endl;
return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Ping() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>* streamer) {
                       return this->StreamedPing(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::org::pytorch::serve::grpc::inference::TorchServeHealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPing(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::org::pytorch::serve::grpc::inference::TorchServeHealthResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Predictions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Predictions() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::org::pytorch::serve::grpc::inference::PredictionsRequest, ::org::pytorch::serve::grpc::inference::PredictionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::org::pytorch::serve::grpc::inference::PredictionsRequest, ::org::pytorch::serve::grpc::inference::PredictionResponse>* streamer) {
                       return this->StreamedPredictions(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Predictions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Predictions(::grpc::ServerContext* /*context*/, const ::org::pytorch::serve::grpc::inference::PredictionsRequest* /*request*/, ::org::pytorch::serve::grpc::inference::PredictionResponse* /*response*/) override {
            std::cout <<"In predictions before abort" << std::endl;

      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPredictions(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::org::pytorch::serve::grpc::inference::PredictionsRequest,::org::pytorch::serve::grpc::inference::PredictionResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Ping<WithStreamedUnaryMethod_Predictions<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Ping<WithStreamedUnaryMethod_Predictions<Service > > StreamedService;
};

}  // namespace inference
}  // namespace grpc
}  // namespace serve
}  // namespace pytorch
}  // namespace org


#endif  // GRPC_inference_2eproto__INCLUDED
