// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: route_guide.proto

#include "route_guide.pb.h"
#include "route_guide.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace routeguide {

static const char* RouteGuide_method_names[] = {
  "/routeguide.RouteGuide/infer",
};

std::unique_ptr< RouteGuide::Stub> RouteGuide::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RouteGuide::Stub> stub(new RouteGuide::Stub(channel, options));
  return stub;
}

RouteGuide::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_infer_(RouteGuide_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RouteGuide::Stub::infer(::grpc::ClientContext* context, const ::routeguide::Jsonfile& request, ::routeguide::Results* response) {
  return ::grpc::internal::BlockingUnaryCall< ::routeguide::Jsonfile, ::routeguide::Results, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_infer_, context, request, response);
}

void RouteGuide::Stub::async::infer(::grpc::ClientContext* context, const ::routeguide::Jsonfile* request, ::routeguide::Results* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::routeguide::Jsonfile, ::routeguide::Results, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_infer_, context, request, response, std::move(f));
}

void RouteGuide::Stub::async::infer(::grpc::ClientContext* context, const ::routeguide::Jsonfile* request, ::routeguide::Results* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_infer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::routeguide::Results>* RouteGuide::Stub::PrepareAsyncinferRaw(::grpc::ClientContext* context, const ::routeguide::Jsonfile& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::routeguide::Results, ::routeguide::Jsonfile, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_infer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::routeguide::Results>* RouteGuide::Stub::AsyncinferRaw(::grpc::ClientContext* context, const ::routeguide::Jsonfile& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncinferRaw(context, request, cq);
  result->StartCall();
  return result;
}

RouteGuide::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RouteGuide_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RouteGuide::Service, ::routeguide::Jsonfile, ::routeguide::Results, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RouteGuide::Service* service,
             ::grpc::ServerContext* ctx,
             const ::routeguide::Jsonfile* req,
             ::routeguide::Results* resp) {
               return service->infer(ctx, req, resp);
             }, this)));
}

RouteGuide::Service::~Service() {
}

::grpc::Status RouteGuide::Service::infer(::grpc::ServerContext* context, const ::routeguide::Jsonfile* request, ::routeguide::Results* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace routeguide

