// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: route_guide.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_route_5fguide_2eproto__INCLUDED
#define GRPC_route_5fguide_2eproto__INCLUDED

#include "route_guide.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace routeguide {

// Interface exported by the server.
class RouteGuide final {
 public:
  static constexpr char const* service_full_name() {
    return "routeguide.RouteGuide";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status infer(::grpc::ClientContext* context, const ::routeguide::Jsonfile& request, ::routeguide::Results* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routeguide::Results>> Asyncinfer(::grpc::ClientContext* context, const ::routeguide::Jsonfile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routeguide::Results>>(AsyncinferRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routeguide::Results>> PrepareAsyncinfer(::grpc::ClientContext* context, const ::routeguide::Jsonfile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routeguide::Results>>(PrepareAsyncinferRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void infer(::grpc::ClientContext* context, const ::routeguide::Jsonfile* request, ::routeguide::Results* response, std::function<void(::grpc::Status)>) = 0;
      virtual void infer(::grpc::ClientContext* context, const ::routeguide::Jsonfile* request, ::routeguide::Results* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::routeguide::Results>* AsyncinferRaw(::grpc::ClientContext* context, const ::routeguide::Jsonfile& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::routeguide::Results>* PrepareAsyncinferRaw(::grpc::ClientContext* context, const ::routeguide::Jsonfile& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status infer(::grpc::ClientContext* context, const ::routeguide::Jsonfile& request, ::routeguide::Results* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routeguide::Results>> Asyncinfer(::grpc::ClientContext* context, const ::routeguide::Jsonfile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routeguide::Results>>(AsyncinferRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routeguide::Results>> PrepareAsyncinfer(::grpc::ClientContext* context, const ::routeguide::Jsonfile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routeguide::Results>>(PrepareAsyncinferRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void infer(::grpc::ClientContext* context, const ::routeguide::Jsonfile* request, ::routeguide::Results* response, std::function<void(::grpc::Status)>) override;
      void infer(::grpc::ClientContext* context, const ::routeguide::Jsonfile* request, ::routeguide::Results* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::routeguide::Results>* AsyncinferRaw(::grpc::ClientContext* context, const ::routeguide::Jsonfile& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::routeguide::Results>* PrepareAsyncinferRaw(::grpc::ClientContext* context, const ::routeguide::Jsonfile& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_infer_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status infer(::grpc::ServerContext* context, const ::routeguide::Jsonfile* request, ::routeguide::Results* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_infer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_infer() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_infer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status infer(::grpc::ServerContext* /*context*/, const ::routeguide::Jsonfile* /*request*/, ::routeguide::Results* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestinfer(::grpc::ServerContext* context, ::routeguide::Jsonfile* request, ::grpc::ServerAsyncResponseWriter< ::routeguide::Results>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_infer<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_infer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_infer() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::routeguide::Jsonfile, ::routeguide::Results>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::routeguide::Jsonfile* request, ::routeguide::Results* response) { return this->infer(context, request, response); }));}
    void SetMessageAllocatorFor_infer(
        ::grpc::MessageAllocator< ::routeguide::Jsonfile, ::routeguide::Results>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::routeguide::Jsonfile, ::routeguide::Results>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_infer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status infer(::grpc::ServerContext* /*context*/, const ::routeguide::Jsonfile* /*request*/, ::routeguide::Results* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* infer(
      ::grpc::CallbackServerContext* /*context*/, const ::routeguide::Jsonfile* /*request*/, ::routeguide::Results* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_infer<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_infer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_infer() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_infer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status infer(::grpc::ServerContext* /*context*/, const ::routeguide::Jsonfile* /*request*/, ::routeguide::Results* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_infer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_infer() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_infer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status infer(::grpc::ServerContext* /*context*/, const ::routeguide::Jsonfile* /*request*/, ::routeguide::Results* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestinfer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_infer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_infer() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->infer(context, request, response); }));
    }
    ~WithRawCallbackMethod_infer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status infer(::grpc::ServerContext* /*context*/, const ::routeguide::Jsonfile* /*request*/, ::routeguide::Results* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* infer(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_infer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_infer() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::routeguide::Jsonfile, ::routeguide::Results>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::routeguide::Jsonfile, ::routeguide::Results>* streamer) {
                       return this->Streamedinfer(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_infer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status infer(::grpc::ServerContext* /*context*/, const ::routeguide::Jsonfile* /*request*/, ::routeguide::Results* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedinfer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::routeguide::Jsonfile,::routeguide::Results>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_infer<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_infer<Service > StreamedService;
};

}  // namespace routeguide


#endif  // GRPC_route_5fguide_2eproto__INCLUDED
